# Generated by Django 5.2 on 2025-04-28 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='الملف')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='الاسم')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('document', 'مستند'), ('video', 'فيديو'), ('other', 'أخرى')], default='other', max_length=10, verbose_name='نوع الوسائط')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'وسائط',
                'verbose_name_plural': 'وسائط',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم العقار')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('property_type', models.CharField(choices=[('residential', 'سكني'), ('commercial', 'تجاري'), ('land', 'أرض'), ('industrial', 'صناعي'), ('mixed_use', 'متعدد الاستخدامات')], max_length=20, verbose_name='نوع العقار')),
                ('building_type', models.CharField(blank=True, choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('building', 'مبنى'), ('farmhouse', 'مزرعة'), ('shop', 'محل تجاري'), ('office', 'مكتب')], max_length=20, null=True, verbose_name='نوع المبنى')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('under_contract', 'تحت العقد'), ('sold', 'مباع'), ('auction', 'في المزاد')], default='available', max_length=20, verbose_name='الحالة')),
                ('deed_number', models.CharField(help_text='رقم صك الملكية الرسمي للعقار', max_length=100, unique=True, verbose_name='رقم الصك')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة (متر مربع)')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='عدد الطوابق')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة البناء')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(max_length=100, verbose_name='المنطقة/المحافظة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('country', models.CharField(default='المملكة العربية السعودية', max_length=100, verbose_name='الدولة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة السوقية')),
                ('minimum_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الحد الأدنى للمزايدة')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='المميزات')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='المرافق')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='الرابط المختصر')),
                ('auction_type', models.CharField(choices=[('sealed', 'مزاد العطاءات المغلقة'), ('reserve', 'مزاد بحد أدنى'), ('no_reserve', 'مزاد بدون حد أدنى')], max_length=20, verbose_name='نوع المزاد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('scheduled', 'مجدول'), ('live', 'مباشر'), ('ended', 'منتهي'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='draft', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='موعد انتهاء التسجيل')),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المزايدة الأولية')),
                ('current_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='المزايدة الحالية')),
                ('minimum_increment', models.DecimalField(decimal_places=2, default=100.0, max_digits=14, verbose_name='الحد الأدنى للزيادة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('bid_count', models.PositiveIntegerField(default=0, verbose_name='عدد المزايدات')),
                ('registered_bidders', models.PositiveIntegerField(default=0, verbose_name='المزايدين المسجلين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='base.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مزاد',
                'verbose_name_plural': 'المزادات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الغرفة')),
                ('room_type', models.CharField(choices=[('bedroom', 'غرفة نوم'), ('bathroom', 'حمام'), ('kitchen', 'مطبخ'), ('living', 'غرفة معيشة'), ('dining', 'غرفة طعام'), ('office', 'مكتب'), ('storage', 'مخزن'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الغرفة')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='الطابق')),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='المساحة (متر مربع)')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='المميزات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='base.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'ordering': ['floor', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ المزايدة')),
                ('bid_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت المزايدة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة'), ('outbid', 'تمت المزايدة بأعلى'), ('winning', 'فائزة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='base.auction', verbose_name='المزاد')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='المزايد')),
            ],
            options={
                'verbose_name': 'مزايدة',
                'verbose_name_plural': 'المزايدات',
                'ordering': ['-bid_time'],
                'indexes': [models.Index(fields=['auction', '-bid_time'], name='base_bid_auction_9a6bc0_idx'), models.Index(fields=['bidder'], name='base_bid_bidder__4ccbc5_idx'), models.Index(fields=['status'], name='base_bid_status_76911a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_number'], name='base_proper_propert_bc4cff_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deed_number'], name='base_proper_deed_nu_983274_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='base_proper_status_3074c3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'property_type'], name='base_proper_city_4e9d13_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['slug'], name='base_auctio_slug_99df50_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['status'], name='base_auctio_status_61d8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['start_date'], name='base_auctio_start_d_11ebd5_idx'),
        ),
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['related_property'], name='base_auctio_related_b9220f_idx'),
        ),
    ]
