# Generated by Django 5.2 on 2025-05-08 22:32

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+999999999'. Max 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone number')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if user has verified their email', verbose_name='Verified')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Verification code')),
                ('verification_code_created', models.DateTimeField(blank=True, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Password reset code')),
                ('reset_code_created', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path, verbose_name='Avatar')),
                ('role', models.CharField(choices=[('owner', 'Property Owner'), ('appraiser', 'Property Appraiser'), ('data_entry', 'Data Entry Specialist'), ('user', 'User')], default='user', max_length=20, verbose_name='User Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة شخصية')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('company_registration', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم تسجيل الشركة')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='المحافظة/الولاية')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الحد الائتماني')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التقييم')),
                ('license_number', models.CharField(blank=True, help_text='رقم ترخيص مزاولة المهنة للوكلاء العقاريين', max_length=50, verbose_name='رقم الترخيص')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الترخيص')),
                ('preferred_locations', models.TextField(blank=True, help_text='قائمة المواقع المفضلة مفصولة بفواصل (أو JSON)', verbose_name='المواقع المفضلة')),
                ('property_preferences', models.TextField(blank=True, help_text='تفضيلات نوع العقار للمشترين (أو JSON)', verbose_name='تفضيلات العقارات')),
            ],
            options={
                'verbose_name': 'ملف تعريف المستخدم',
                'verbose_name_plural': 'ملفات تعريف المستخدمين',
            },
        ),
    ]
