# Generated by Django 5.2 on 2025-05-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Property Owner'), ('appraiser', 'Property Appraiser'), ('data_entry', 'Data Entry Specialist')], default='user', max_length=20, verbose_name='User Role'),
        ),
    ]
