# Generated by Django 5.2 on 2025-05-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Property Owner'), ('appraiser', 'Property Appraiser'), ('data_entry', 'Data Entry Specialist'), ('user', 'User')], default='user', max_length=20, verbose_name='User Role'),
        ),
    ]
